const STORAGE='spider_training_pro_v3';
const defaultState={level:'Foundation',daysPerWeek:4,rest:60,logs:[],photos:[],xp:0,adapt:1,voice:true,spokenCount:true,vibration:true,voiceURI:'',voiceRate:.95,birthday:'10-21'};
let state=Object.assign({},defaultState,JSON.parse(localStorage.getItem(STORAGE)||'{}'));
let currentWorkout=null,currentExerciseIndex=0,currentSet=1,phase='work',timerSec=0,timerHandle=null,lastEffort='normal';
let demoRunning=true,demoTime=0,viewAngle=.45,lastFrame=performance.now();
const $=id=>document.getElementById(id);
function save(){localStorage.setItem(STORAGE,JSON.stringify(state));}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._h);t._h=setTimeout(()=>t.classList.remove('show'),1800)}
function vibrate(pattern=40){if(state.vibration&&navigator.vibrate)navigator.vibrate(pattern)}
function show(screen){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(screen).classList.add('active');document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.screen===screen));renderAll();scrollTo(0,0)}
document.querySelectorAll('.bottom-nav button').forEach(b=>b.addEventListener('click',()=>show(b.dataset.screen)));

function birthdayInfo(){const now=new Date(),[m,d]=state.birthday.split('-').map(Number);let target=new Date(now.getFullYear(),m-1,d,23,59,59);if(target<now)target=new Date(now.getFullYear()+1,m-1,d,23,59,59);const days=Math.ceil((target-now)/86400000);const yearStart=new Date(target.getFullYear()-1,m-1,d);const total=(target-yearStart)/86400000;return{days,pct:Math.max(0,Math.min(100,(1-days/total)*100))}}
function workoutOrder(){const base=['Push + Core','Pernas + Core','Costas + Braços + Core','Cindy Adaptado'];if(state.daysPerWeek>=5)base.push('Calistenia Full Body');return base}
function nextWorkoutName(){const o=workoutOrder();return o[state.logs.length%o.length]}
function doseFor(id){const e=EXERCISES[id],l=LEVELS[state.level],a=state.adapt;let n=l.rep;if(/Pernas|glúteos|Panturrilhas/.test(e.group))n=l.legs;if(/Abdômen|Core|core|Costas/.test(e.group))n=l.core;if(['plank','sidePlank','hollow','pseudoLean'].includes(id))return{kind:'time',value:Math.max(10,Math.round(l.hold*a)),label:`${Math.max(10,Math.round(l.hold*a))}s`};if(id==='selfCurl')return{kind:'reps',value:Math.max(6,Math.round(l.rep*a)),label:`${Math.max(6,Math.round(l.rep*a))} reps/lado`};return{kind:'reps',value:Math.max(4,Math.round(n*a)),label:`${Math.max(4,Math.round(n*a))} reps`}}
function coachText(){if(!state.logs.length)return'Comece com técnica limpa. O app sobe o volume apenas quando você sinaliza que o treino ficou confortável.';const x=state.logs.at(-1);if(x.effort==='easy')return'Último treino ficou fácil: aumentei levemente o próximo estímulo.';if(x.effort==='hard')return'Última sessão pesou: reduzi um pouco o volume para preservar a técnica.';if(x.effort==='bad')return'Recuperação primeiro. O próximo treino vem mais leve; retome sem pressa.';return'Progressão estável. Tente melhorar execução antes de buscar mais repetições.'}
function renderHome(){const b=birthdayInfo(),next=nextWorkoutName();$('nextWorkoutTitle').textContent=next;$('nextWorkoutMeta').textContent=`${state.level} • ${PROGRAMS[next].length} exercícios • ${LEVELS[state.level].sets} séries`;$('levelBadge').textContent=state.level.toUpperCase();$('daysLeft').textContent=`${b.days} dias`;$('goalProgress').style.width=b.pct+'%';$('streak').textContent=currentStreak();$('completed').textContent=state.logs.length;$('consistency').textContent=consistency()+'%';$('xp').textContent=state.xp;$('coachMessage').textContent=coachText();renderWeek()}
function consistency(){const recent=state.logs.filter(l=>Date.now()-new Date(l.date)<28*86400000).length;return Math.min(100,Math.round(recent/(state.daysPerWeek*4)*100))}
function currentStreak(){const ds=[...new Set(state.logs.map(l=>l.date.slice(0,10)))].sort().reverse();if(!ds.length)return 0;let n=0,cursor=new Date();cursor.setHours(0,0,0,0);for(const d of ds){const dt=new Date(d+'T00:00:00'),diff=Math.round((cursor-dt)/86400000);if(diff===0||diff===1){n++;cursor=dt}else break}return n}
function bestStreak(){const ds=[...new Set(state.logs.map(l=>l.date.slice(0,10)))].sort();let best=0,run=0,last=null;for(const d of ds){const dt=new Date(d+'T00:00:00');run=last&&Math.round((dt-last)/86400000)===1?run+1:1;best=Math.max(best,run);last=dt}return best}
function renderWeek(){const box=$('weekStrip');box.innerHTML='';const today=new Date();for(let i=6;i>=0;i--){const d=new Date(today);d.setDate(today.getDate()-i);const key=d.toISOString().slice(0,10),done=state.logs.some(l=>l.date.startsWith(key));const el=document.createElement('div');el.className='day-dot'+(done?' done':'')+(i===0?' today':'');el.innerHTML=`${['D','S','T','Q','Q','S','S'][d.getDay()]}<i>${d.getDate()}</i>`;box.appendChild(el)}}

function renderPlan(){ $('levelSelect').value=state.level;$('daysPerWeek').value=String(state.daysPerWeek);$('restSelect').value=String(state.rest);const list=$('planList');list.innerHTML='';for(const [name,ids] of Object.entries(PROGRAMS)){const card=document.createElement('article');card.className='card';card.innerHTML=`<div class="card-title">${name}</div><div class="muted smalltext">${ids.length} exercícios</div>`+ids.map(id=>`<div class="exercise-row"><div><div class="exercise-name">${EXERCISES[id].name}</div><div class="exercise-meta">${EXERCISES[id].group}</div></div><div class="exercise-dose">${doseFor(id).label}</div></div>`).join('')+`<button class="secondary" data-start-plan="${name}">INICIAR ESTE TREINO</button>`;list.appendChild(card)}list.querySelectorAll('[data-start-plan]').forEach(b=>b.onclick=()=>startWorkoutByName(b.dataset.startPlan))}

function renderLibrary(filter=''){const q=filter.trim().toLowerCase(),box=$('exerciseLibrary');box.innerHTML='';Object.entries(EXERCISES).filter(([id,e])=>!q||(`${e.name} ${e.group}`).toLowerCase().includes(q)).forEach(([id,e])=>{const card=document.createElement('article');card.className='card library-item';card.innerHTML=`<div class="card-title">${e.name}</div><div class="muted smalltext">${e.group}</div><p>${e.cue}</p><button class="secondary" data-demo="${id}">VER DEMONSTRAÇÃO 3D</button>`;box.appendChild(card)});box.querySelectorAll('[data-demo]').forEach(b=>b.onclick=()=>previewExercise(b.dataset.demo))}
function previewExercise(id){currentWorkout={name:'Demonstração',ids:[id],preview:true};currentExerciseIndex=0;currentSet=1;show('train');renderTraining();speak(`${EXERCISES[id].name}. ${EXERCISES[id].cue}`)}

function startWorkoutByName(name){if(!PROGRAMS[name])return;currentWorkout={name,ids:PROGRAMS[name],preview:false,start:Date.now()};currentExerciseIndex=0;currentSet=1;phase='work';timerSec=0;lastEffort='normal';show('train');renderTraining();announceCurrent()}
function startWorkout(){startWorkoutByName(nextWorkoutName())}
function renderTraining(){if(!currentWorkout)return;const id=currentWorkout.ids[currentExerciseIndex],e=EXERCISES[id],dose=doseFor(id);$('workoutTitle').textContent=currentWorkout.name;$('exerciseCounter').textContent=`Exercício ${currentExerciseIndex+1} / ${currentWorkout.ids.length}`;$('setCounter').textContent=currentWorkout.preview?'DEMO':`Série ${currentSet}/${LEVELS[state.level].sets}`;$('exerciseName').textContent=e.name;$('exerciseDose').textContent=dose.label;$('exerciseCue').textContent=e.cue;$('instructionList').innerHTML=e.steps.map(s=>`<li>${s}</li>`).join('');$('mistakeList').textContent='Evite: '+e.mistakes;$('sessionProgress').style.width=((currentExerciseIndex+(currentSet-1)/LEVELS[state.level].sets)/currentWorkout.ids.length*100)+'%';$('phaseLabel').textContent=phase==='rest'?'DESCANSO':'EXECUÇÃO';$('timer').textContent=fmt(timerSec)}
function fmt(s){return`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function completeSet(){if(!currentWorkout)return;if(currentWorkout.preview){show('library');return}const sets=LEVELS[state.level].sets;if(currentSet<sets){currentSet++;startRest()}else if(currentExerciseIndex<currentWorkout.ids.length-1){currentExerciseIndex++;currentSet=1;startRest(true)}else finishWorkout(lastEffort)}
function startRest(nextExercise=false){stopTimer();phase='rest';timerSec=state.rest;renderTraining();speak(nextExercise?`Descanso. Próximo exercício: ${EXERCISES[currentWorkout.ids[currentExerciseIndex]].name}.`:'Descanso. Respire e prepare a próxima série.');timerHandle=setInterval(()=>{timerSec--;if(state.spokenCount&&[30,20,10,5,4,3,2,1].includes(timerSec))speak(timerSec<=5?String(timerSec):`${timerSec} segundos`);if(timerSec<=0){stopTimer();phase='work';timerSec=0;vibrate([60,50,60]);renderTraining();announceCurrent()}else renderTraining()},1000)}
function toggleTimer(){if(timerHandle){stopTimer();return}timerHandle=setInterval(()=>{timerSec++;renderTraining()},1000)}
function stopTimer(){clearInterval(timerHandle);timerHandle=null}
function finishWorkout(effort='normal'){if(!currentWorkout||currentWorkout.preview)return;stopTimer();const minutes=Math.max(1,Math.round((Date.now()-currentWorkout.start)/60000));state.logs.push({date:new Date().toISOString(),workout:currentWorkout.name,level:state.level,effort,minutes});state.xp+=25+PROGRAMS[currentWorkout.name].length*5;if(effort==='easy')state.adapt=Math.min(1.25,state.adapt+.05);if(effort==='hard')state.adapt=Math.max(.8,state.adapt-.05);if(effort==='bad')state.adapt=Math.max(.7,state.adapt-.1);if(effort==='normal')state.adapt+= (1-state.adapt)*.35;save();speak('Treino concluído. Boa sessão. Hidrate-se e recupere bem.');vibrate([80,50,80]);toast('Treino concluído ✓');currentWorkout=null;show('home')}
function announceCurrent(){if(!currentWorkout)return;const id=currentWorkout.ids[currentExerciseIndex],e=EXERCISES[id],d=doseFor(id);speak(`${e.name}. ${d.label}. ${e.cue}`);if(state.spokenCount&&d.kind==='reps'&&!currentWorkout.preview)paceReps(d.value)}
let repTimers=[];function paceReps(n){repTimers.forEach(clearTimeout);repTimers=[];for(let i=1;i<=n;i++){repTimers.push(setTimeout(()=>{if(phase==='work')speak(String(i))},i*2600))}}

function populateVoices(){const voices=speechSynthesis.getVoices(),sel=$('voiceSelect');const current=state.voiceURI;sel.innerHTML='';voices.filter(v=>v.lang.toLowerCase().startsWith('pt')).forEach(v=>{const o=document.createElement('option');o.value=v.voiceURI;o.textContent=`${v.name} (${v.lang})`;sel.appendChild(o)});if(!sel.options.length){voices.forEach(v=>{const o=document.createElement('option');o.value=v.voiceURI;o.textContent=`${v.name} (${v.lang})`;sel.appendChild(o)})}if(current)sel.value=current}
function speak(text){if(!state.voice||!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text),voices=speechSynthesis.getVoices();u.lang='pt-BR';u.rate=state.voiceRate;const v=voices.find(v=>v.voiceURI===state.voiceURI)||voices.find(v=>v.lang==='pt-BR')||voices.find(v=>v.lang.startsWith('pt'));if(v)u.voice=v;speechSynthesis.speak(u)}
if('speechSynthesis'in window){speechSynthesis.onvoiceschanged=populateVoices;setTimeout(populateVoices,100)}

function renderProgress(){ $('totalMinutes').textContent=state.logs.reduce((a,b)=>a+(b.minutes||0),0);$('bestStreak').textContent=bestStreak();const easy=state.logs.filter(l=>l.effort==='easy'||l.effort==='normal').length;$('easyRate').textContent=(state.logs.length?Math.round(easy/state.logs.length*100):0)+'%';$('currentLevelMetric').textContent=state.level.slice(0,3).toUpperCase();$('history').innerHTML=state.logs.slice(-10).reverse().map(l=>`<div class="history-row"><div><strong>${l.workout}</strong><br><small>${new Date(l.date).toLocaleDateString('pt-BR')} • ${l.level}</small></div><div><small>${l.effort} • ${l.minutes}min</small></div></div>`).join('')||'<p class="muted">Nenhum treino concluído ainda.</p>';$('photoGrid').innerHTML=state.photos.slice().reverse().map(p=>`<img src="${p.data}" alt="Check-in de ${new Date(p.date).toLocaleDateString('pt-BR')}">`).join('')}

function renderSettings(){ $('voiceRate').value=state.voiceRate;$('spokenCount').checked=state.spokenCount;$('vibrationToggle').checked=state.vibration;$('voiceToggle').textContent=state.voice?'🔊':'🔇';populateVoices()}
function renderAll(){renderHome();renderPlan();renderProgress();renderSettings();if($('library').classList.contains('active'))renderLibrary($('exerciseSearch').value)}

$('startWorkout').onclick=startWorkout;$('exitWorkout').onclick=()=>{stopTimer();currentWorkout=null;show('home')};$('completeSet').onclick=completeSet;$('timerToggle').onclick=toggleTimer;$('toggleDemo').onclick=()=>{demoRunning=!demoRunning;$('toggleDemo').textContent=demoRunning?'PAUSAR DEMO':'CONTINUAR DEMO'};$('rotateView').onclick=()=>viewAngle+=.55;document.querySelectorAll('.effort').forEach(b=>b.onclick=()=>{lastEffort=b.dataset.effort;toast('Esforço: '+b.textContent.trim())});
$('levelSelect').onchange=e=>{state.level=e.target.value;state.adapt=1;save();renderAll()};$('daysPerWeek').onchange=e=>{state.daysPerWeek=Number(e.target.value);save();renderAll()};$('restSelect').onchange=e=>{state.rest=Number(e.target.value);save();renderAll()};$('exerciseSearch').oninput=e=>renderLibrary(e.target.value);
$('voiceToggle').onclick=()=>{state.voice=!state.voice;save();renderSettings();if(state.voice)speak('Coach de voz ativado.')};$('voiceSelect').onchange=e=>{state.voiceURI=e.target.value;save()};$('voiceRate').oninput=e=>{state.voiceRate=Number(e.target.value);save()};$('spokenCount').onchange=e=>{state.spokenCount=e.target.checked;save()};$('vibrationToggle').onchange=e=>{state.vibration=e.target.checked;save()};$('testVoice').onclick=()=>speak('Coach ativado. Vou anunciar o exercício, contar o ritmo, avisar o descanso e chamar o próximo movimento.');
$('photoInput').onchange=e=>{const f=e.target.files[0];if(!f)return;if(f.size>5*1024*1024)return toast('Escolha uma foto menor que 5 MB');const r=new FileReader();r.onload=()=>{state.photos.push({date:new Date().toISOString(),data:r.result});state.photos=state.photos.slice(-12);save();renderProgress();toast('Check-in salvo localmente')};r.readAsDataURL(f)};
$('exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='spider-training-backup.json';a.click();URL.revokeObjectURL(a.href)};$('importBtn').onclick=()=>$('importInput').click();$('importInput').onchange=e=>{const r=new FileReader();r.onload=()=>{try{state=Object.assign({},defaultState,JSON.parse(r.result));save();renderAll();toast('Backup importado')}catch{toast('Arquivo de backup inválido')}};r.readAsText(e.target.files[0])};$('resetData').onclick=()=>{if(confirm('Apagar histórico, fotos e preferências deste aparelho?')){localStorage.removeItem(STORAGE);state={...defaultState};renderAll();toast('Dados apagados')}};

// 3D articulated mannequin: simple keyframe-based projection, no external library.
const C=$('motionCanvas'),ctx=C.getContext('2d');
function pose(mode,t){const s=Math.sin(t*Math.PI*2),u=(s+1)/2;let p={head:[0,2.4,0],neck:[0,1.9,0],hip:[0,.5,0],lh:[-.75,1.5,0],rh:[.75,1.5,0],le:[-.6,.8,0],re:[.6,.8,0],lk:[-.42,-.7,0],rk:[.42,-.7,0],lf:[-.45,-2,0],rf:[.45,-2,0]};
 const set=(k,a)=>p[k]=a;
 if(mode==='squat'){const y=-u*.85;set('hip',[0,.5+y,0]);set('head',[0,2.4+y*.45,0]);set('neck',[0,1.9+y*.55,0]);set('lk',[-.65,-.1-u*.45,.25]);set('rk',[.65,-.1-u*.45,-.25]);}
 if(mode==='lunge'){set('hip',[0,.5-u*.65,0]);set('lk',[-.7,-.25-u*.35,.3]);set('lf',[-1.1,-2,.4]);set('rk',[.55,-.8-u*.45,-.4]);set('rf',[1.1,-2,-.6]);}
 if(['pushup','pushupKnee','plank','lean'].includes(mode)){const bend=mode==='pushup'?u*.65:mode==='pushupKnee'?u*.6:0;set('head',[1.7,1-bend,0]);set('neck',[1.25,.8-bend*.8,0]);set('hip',[0,.35,0]);set('lh',[1.05,.15, .45]);set('rh',[1.05,.15,-.45]);set('le',[.7,.35-bend*.4,.4]);set('re',[.7,.35-bend*.4,-.4]);set('lk',[-.95,.12, mode==='pushupKnee'?.45:.2]);set('rk',[-.95,.12, mode==='pushupKnee'?-.45:-.2]);set('lf',[-1.9,.05,.2]);set('rf',[-1.9,.05,-.2]);if(mode==='lean'){set('head',[1.95,1.1,0]);set('neck',[1.5,.9,0]);}}
 if(mode==='pike'){set('hip',[0,2,0]);set('head',[1.25,.75-u*.35,0]);set('neck',[.9,1.05-u*.25,0]);set('lh',[1.2,.05,.4]);set('rh',[1.2,.05,-.4]);set('le',[.85,.45-u*.25,.4]);set('re',[.85,.45-u*.25,-.4]);set('lk',[-.65,.45,.2]);set('rk',[-.65,.45,-.2]);set('lf',[-1.4,.05,.2]);set('rf',[-1.4,.05,-.2]);}
 if(mode==='bridge'){set('head',[1.55,.15,0]);set('neck',[1.1,.18,0]);set('hip',[0,.25+u*.9,0]);set('lk',[-.7,.8,.3]);set('rk',[-.7,.8,-.3]);set('lf',[-1.35,.05,.35]);set('rf',[-1.35,.05,-.35]);}
 if(mode==='crunch'){set('head',[1.1,.3+u*.45,0]);set('neck',[.7,.25+u*.35,0]);set('hip',[0,.1,0]);set('lk',[-.45,.85+u*.25,.2]);set('rk',[-.45,.85+u*.25,-.2]);set('lf',[-.9,.35+u*.45,.2]);set('rf',[-.9,.35+u*.45,-.2]);}
 if(mode==='legraise'){set('head',[1.5,.18,0]);set('neck',[1.1,.15,0]);set('hip',[0,.1,0]);const a=u*1.2;set('lk',[-.3+Math.sin(a)*1.2,.1+Math.sin(a)*1.4,.2]);set('rk',[-.3+Math.sin(a)*1.2,.1+Math.sin(a)*1.4,-.2]);set('lf',[-1+Math.sin(a)*2,.1+Math.sin(a)*2.2,.2]);set('rf',[-1+Math.sin(a)*2,.1+Math.sin(a)*2.2,-.2]);}
 if(['deadbug','birdDog','mountain'].includes(mode)){if(mode==='deadbug'){set('head',[1.2,.2,0]);set('neck',[.85,.15,0]);set('hip',[0,.1,0]);set('lh',[.2,1.4,.5]);set('rh',[.6,.65+u*.75,-.5]);set('lk',[-.4,1,.25]);set('rk',[-.8+u*1.2,.25+u*.7,-.25]);set('lf',[-.8,.35,.25]);set('rf',[-1.5+u*2.3,.1+u*.3,-.25]);}else{set('head',[1.2,1.05,0]);set('neck',[.8,.9,0]);set('hip',[0,.65,0]);set('lh',[.55,.05,.5]);set('rh',[.55,.05,-.5]);set('lk',[-.65,.05,.35]);set('rk',[-.65,.05,-.35]);set('lf',[-.95,.02,.35]);set('rf',[-.95,.02,-.35]);if(mode==='birdDog'){set('rh',[1.65,1.2,-.2]);set('rf',[-1.75,1.0,-.2]);}else{set('lk',[-.1+u*.8,.2+u*.4,.35]);set('lf',[.25+u*.8,.05+u*.35,.35]);}}
 }
 if(['superman','snowAngel','ytw','swimmer'].includes(mode)){set('head',[1.4,.3+u*.12,0]);set('neck',[1,.25+u*.1,0]);set('hip',[0,.12,0]);set('lk',[-.9,.12+u*.1,.25]);set('rk',[-.9,.12+u*.1,-.25]);set('lf',[-1.8,.15+u*.18,.25]);set('rf',[-1.8,.15+u*.18,-.25]);const spread=mode==='snowAngel'?Math.cos(t*Math.PI*2)*1.1:mode==='ytw'?.75:1.1;set('lh',[.8,.25+u*.2,spread]);set('rh',[.8,.25+u*.2,-spread]);if(mode==='swimmer'){set('lh',[1.2,.45+u*.25,.2]);set('rf',[-1.8,.15+u*.35,-.25]);}}
 if(mode==='sidePlank'){set('head',[1.4,1.5,0]);set('neck',[1.05,1.25,0]);set('hip',[0,.65,0]);set('lh',[.2,.05,.15]);set('rh',[.2,1.85,-.1]);set('lf',[-1.5,.05,.15]);set('rf',[-1.5,.15,-.15]);}
 if(mode==='hollow'){set('head',[1.3,.35,0]);set('neck',[.95,.25,0]);set('hip',[0,.08,0]);set('lh',[1.8,.75,.2]);set('rh',[1.8,.75,-.2]);set('lf',[-1.7,.55,.2]);set('rf',[-1.7,.55,-.2]);}
 if(mode==='calf'){const y=u*.35;Object.keys(p).forEach(k=>p[k]=[p[k][0],p[k][1]+y,p[k][2]]);}
 if(mode==='curl'){set('lh',[-.55,1.35,.3]);set('rh',[.3,.7+u*.8,-.2]);set('le',[-.45,.8,.25]);set('re',[.45,.8,-.25]);}
 return p}
function project(v){const [x,y,z]=v,c=Math.cos(viewAngle),s=Math.sin(viewAngle),xr=x*c-z*s,zr=x*s+z*c,scale=85/(1+zr*.08);return[C.width/2+xr*scale,C.height/2-y*scale]}
function drawBone(a,b,p){const A=project(p[a]),B=project(p[b]);ctx.beginPath();ctx.moveTo(...A);ctx.lineTo(...B);ctx.stroke()}
function drawDemo(now){if(demoRunning)demoTime+=(now-lastFrame)/2200;lastFrame=now;ctx.clearRect(0,0,C.width,C.height);ctx.save();ctx.strokeStyle='#eef2f6';ctx.fillStyle='#eef2f6';ctx.lineWidth=9;ctx.lineCap='round';ctx.globalAlpha=.95;const id=currentWorkout?currentWorkout.ids[currentExerciseIndex]:'pushup',p=pose(EXERCISES[id]?.mode||'pushup',demoTime%1);[['head','neck'],['neck','hip'],['neck','le'],['le','lh'],['neck','re'],['re','rh'],['hip','lk'],['lk','lf'],['hip','rk'],['rk','rf']].forEach(b=>drawBone(b[0],b[1],p));const H=project(p.head);ctx.beginPath();ctx.arc(H[0],H[1],22,0,Math.PI*2);ctx.fill();ctx.globalAlpha=.22;ctx.strokeStyle='#8190a6';ctx.lineWidth=2;for(let i=-3;i<=3;i++){const a=project([i,-2.15,-2]),b=project([i,-2.15,2]);ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.stroke()}ctx.restore();requestAnimationFrame(drawDemo)}requestAnimationFrame(drawDemo);

// iOS/PWA install hint and service worker
const standalone=window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true;const isIOS=/iPhone|iPad|iPod/.test(navigator.userAgent);if(isIOS&&!standalone&&!sessionStorage.getItem('installDismissed'))$('installBanner').classList.remove('hidden');$('dismissInstall').onclick=()=>{$('installBanner').classList.add('hidden');sessionStorage.setItem('installDismissed','1')};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
renderLibrary();renderAll();
