const EXERCISES = {
  pushup:{name:'Flexão',group:'Peito • tríceps • core',mode:'pushup',cue:'Corpo em bloco; peito desce entre as mãos.',steps:['Mãos um pouco além da largura dos ombros.','Contraia abdômen e glúteos para manter cabeça, quadril e calcanhares alinhados.','Desça controlando até o peito se aproximar do chão.','Empurre o chão sem deixar o quadril cair.'],mistakes:'Evite abrir demais os cotovelos, perder a linha do corpo ou encurtar a amplitude.'},
  kneePushup:{name:'Flexão com joelhos',group:'Peito • tríceps',mode:'pushupKnee',cue:'Mesma técnica da flexão, com apoio dos joelhos.',steps:['Apoie joelhos e mãos no chão.','Crie uma linha reta dos joelhos à cabeça.','Desça o peito entre as mãos.','Empurre o chão mantendo abdômen firme.'],mistakes:'Não dobre o quadril para “roubar” a repetição.'},
  diamond:{name:'Flexão fechada',group:'Tríceps • peito',mode:'pushup',cue:'Mãos mais próximas; cotovelos seguem perto do tronco.',steps:['Posicione as mãos um pouco mais fechadas que na flexão comum.','Mantenha o tronco firme.','Desça com cotovelos apontando para trás.','Suba sem perder a linha do corpo.'],mistakes:'Não precisa formar um diamante perfeito se isso incomodar o punho.'},
  pike:{name:'Pike push-up',group:'Ombros • tríceps',mode:'pike',cue:'Quadril alto; cabeça desce à frente das mãos.',steps:['Comece em posição de V invertido.','Mãos firmes e quadril alto.','Dobre os cotovelos levando a cabeça em direção ao chão, um pouco à frente das mãos.','Empurre até estender os braços.'],mistakes:'Evite transformar o movimento em flexão comum deixando o quadril cair.'},
  pseudoLean:{name:'Pseudo-planche lean',group:'Ombros • peito • core',mode:'lean',cue:'Incline o corpo à frente com braços estendidos.',steps:['Entre em prancha alta.','Gire levemente os dedos para fora se necessário.','Sem dobrar os braços, leve os ombros alguns centímetros à frente das mãos.','Segure mantendo escápulas ativas e abdômen firme.'],mistakes:'Aumente a inclinação aos poucos; não force punhos doloridos.'},
  squat:{name:'Agachamento',group:'Quadríceps • glúteos',mode:'squat',cue:'Joelhos acompanham os pés; quadril desce controlado.',steps:['Pés aproximadamente na largura dos ombros.','Empurre o quadril para trás e para baixo.','Mantenha o peito aberto e joelhos acompanhando a direção dos pés.','Suba empurrando o chão.'],mistakes:'Evite colapsar os joelhos para dentro ou arredondar muito a lombar.'},
  reverseLunge:{name:'Afundo reverso',group:'Pernas • glúteos',mode:'lunge',cue:'Passo para trás; tronco alto; joelho da frente estável.',steps:['Fique em pé com pés paralelos.','Dê um passo para trás e desça os dois joelhos.','Mantenha o pé da frente inteiro no chão.','Empurre o chão com a perna da frente para voltar.'],mistakes:'Não deixe o joelho da frente cair para dentro.'},
  splitSquat:{name:'Split squat',group:'Pernas • glúteos',mode:'lunge',cue:'Base dividida fixa; sobe e desce verticalmente.',steps:['Adote uma passada confortável e mantenha os pés no lugar.','Desça o joelho de trás em direção ao chão.','Mantenha o tronco alto.','Suba usando principalmente a perna da frente.'],mistakes:'Se perder equilíbrio, reduza a amplitude.'},
  calfRaise:{name:'Elevação de panturrilha',group:'Panturrilhas',mode:'calf',cue:'Suba alto na ponta dos pés e desça devagar.',steps:['Pés paralelos e postura alta.','Eleve os calcanhares o máximo confortável.','Segure um instante no topo.','Desça controlando.'],mistakes:'Evite quicar rapidamente no chão.'},
  gluteBridge:{name:'Ponte de glúteos',group:'Glúteos • posterior',mode:'bridge',cue:'Aperte os glúteos no topo sem hiperestender a lombar.',steps:['Deite de costas, joelhos dobrados e pés no chão.','Contraia o abdômen.','Eleve o quadril apertando os glúteos.','Desça devagar até quase tocar o chão.'],mistakes:'Não compense arqueando exageradamente a lombar.'},
  plank:{name:'Prancha',group:'Core',mode:'plank',cue:'Costelas para baixo; glúteos e abdômen contraídos.',steps:['Apoie antebraços e pontas dos pés.','Mantenha cotovelos abaixo dos ombros.','Contraia abdômen e glúteos.','Respire sem perder a posição.'],mistakes:'Evite quadril caído ou elevado demais.'},
  sidePlank:{name:'Prancha lateral',group:'Core • oblíquos',mode:'sidePlank',cue:'Corpo forma uma linha da cabeça aos pés.',steps:['Apoie um antebraço abaixo do ombro.','Empilhe ou escalone os pés.','Eleve o quadril.','Mantenha peito aberto e respire.'],mistakes:'Não deixe o quadril desabar para o chão.'},
  deadBug:{name:'Dead bug',group:'Abdômen • estabilidade',mode:'deadbug',cue:'Lombar controlada enquanto braço e perna se afastam.',steps:['Deite de costas com braços para cima e joelhos a 90°.','Contraia o abdômen mantendo a lombar estável.','Estenda braço e perna opostos lentamente.','Volte e alterne os lados.'],mistakes:'Diminua a amplitude se a lombar começar a arquear.'},
  reverseCrunch:{name:'Reverse crunch',group:'Abdômen',mode:'crunch',cue:'Enrole a pelve; não balance as pernas.',steps:['Deite com joelhos dobrados.','Leve os joelhos em direção ao peito.','Enrole levemente a pelve tirando o cóccix do chão.','Desça devagar sem balançar.'],mistakes:'Evite usar impulso das pernas.'},
  legRaise:{name:'Elevação de pernas',group:'Abdômen',mode:'legraise',cue:'Desça só até onde a lombar continua controlada.',steps:['Deite de costas com pernas estendidas ou levemente dobradas.','Contraia o abdômen.','Eleve as pernas controladamente.','Desça até antes de perder a posição da lombar.'],mistakes:'Reduza amplitude ou dobre os joelhos se sentir a lombar arqueando.'},
  hollow:{name:'Hollow hold',group:'Abdômen • core',mode:'hollow',cue:'Costelas fechadas e lombar controlada no chão.',steps:['Deite de costas.','Eleve ombros e pernas.','Aproxime costelas da pelve mantendo abdômen tenso.','Ajuste braços/pernas para uma dificuldade sustentável.'],mistakes:'Não mantenha a versão avançada se a lombar perder contato/controle.'},
  mountain:{name:'Mountain climber',group:'Core • condicionamento',mode:'mountain',cue:'Prancha firme enquanto joelhos alternam.',steps:['Comece em prancha alta.','Leve um joelho em direção ao peito.','Troque as pernas mantendo quadril estável.','Acelere apenas se conseguir preservar a forma.'],mistakes:'Evite pular com quadril balançando muito.'},
  birdDog:{name:'Bird dog',group:'Costas • core',mode:'birdDog',cue:'Alcance longe com braço e perna opostos.',steps:['Fique em quatro apoios.','Contraia suavemente o abdômen.','Estenda braço e perna opostos sem girar o quadril.','Retorne e troque o lado.'],mistakes:'Não eleve a perna acima da linha do tronco.'},
  superman:{name:'Superman controlado',group:'Lombar • cadeia posterior',mode:'superman',cue:'Elevação pequena e controlada; pescoço neutro.',steps:['Deite de barriga para baixo.','Estenda braços e pernas.','Eleve braços e pernas alguns centímetros.','Segure brevemente e desça devagar.'],mistakes:'Não force uma hiperextensão grande da lombar ou do pescoço.'},
  snowAngel:{name:'Reverse snow angel',group:'Costas • escápulas',mode:'snowAngel',cue:'Braços deslizam em arco com escápulas ativas.',steps:['Deite de barriga para baixo.','Eleve levemente mãos e peito se confortável.','Mova os braços em arco da linha do quadril até acima da cabeça.','Volte mantendo o movimento lento.'],mistakes:'Não encolha os ombros em direção às orelhas.'},
  ytw:{name:'Prone Y-T-W',group:'Costas • ombros posteriores',mode:'ytw',cue:'Movimentos pequenos; foco nas escápulas.',steps:['Deite de barriga para baixo.','Forme um Y com os braços e eleve levemente.','Depois um T.','Depois um W puxando cotovelos para baixo e para trás.'],mistakes:'Use pouca amplitude e evite compensar pela lombar.'},
  swimmer:{name:'Swimmer',group:'Costas • posterior',mode:'swimmer',cue:'Braço e perna opostos alternam de forma curta.',steps:['Deite de barriga para baixo.','Eleve levemente braço direito e perna esquerda.','Troque lentamente.','Mantenha o pescoço neutro.'],mistakes:'Não precisa levantar alto; qualidade e controle importam mais.'},
  selfCurl:{name:'Rosca auto-resistida',group:'Bíceps',mode:'curl',cue:'Uma mão cria resistência enquanto a outra flexiona o cotovelo.',steps:['Mantenha o cotovelo junto ao corpo.','Use a mão oposta para oferecer resistência ao antebraço que sobe.','Faça a flexão lentamente por 3–4 segundos.','Na descida, mantenha resistência com a mão oposta.'],mistakes:'A resistência deve ser firme, mas suave o bastante para completar o movimento sem dor.'}
};

const PROGRAMS={
 'Push + Core':['pushup','pike','diamond','deadBug','reverseCrunch','plank'],
 'Cindy Adaptado':['pushup','squat','mountain','plank'],
 'Pernas + Core':['squat','reverseLunge','gluteBridge','calfRaise','reverseCrunch','sidePlank'],
 'Costas + Braços + Core':['snowAngel','ytw','birdDog','selfCurl','superman','hollow'],
 'Spider Core':['deadBug','reverseCrunch','legRaise','hollow','sidePlank','mountain'],
 'Calistenia Full Body':['pushup','pike','squat','reverseLunge','birdDog','selfCurl','plank'],
 'Skill & Controle':['pseudoLean','pike','splitSquat','hollow','birdDog','calfRaise']
};

const LEVELS={
 Foundation:{sets:2,rep:6,core:8,legs:10,hold:20,rest:60},
 Beginner:{sets:3,rep:8,core:10,legs:12,hold:30,rest:60},
 Intermediate:{sets:3,rep:10,core:12,legs:15,hold:40,rest:60},
 Advanced:{sets:4,rep:12,core:15,legs:18,hold:50,rest:75}
};
